### ISSUE TITLE
Sistema com métricas básicas para a Legacy

### ISSUE THREAD

**Issue by ErFer7** [PedroBinotto/metrify#9]
- [x] Configurações do projeto
- [x] Documentação inicial
- [x] Sistema de autenticação inicial
- [x] Comunicação com o GitHub
- [x] #12 
- [ ] #21
- [ ] #10 
- [x] #14 
- [ ] #18
- [ ] #19
- [ ] #11
- [ ] #13
